# Generated by Django 5.1.7 on 2025-03-25 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=30)),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Presentations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presentation', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/pres/', verbose_name='Файл презентации')),
                ('adress', models.CharField(default='0', max_length=100)),
                ('square', models.CharField(default='0', max_length=20)),
                ('power', models.CharField(default='0', max_length=20)),
                ('water_supply', models.CharField(default='0', max_length=30)),
                ('height', models.CharField(default='0', max_length=20)),
                ('rate', models.CharField(default='0', max_length=20)),
                ('type_rent', models.CharField(default='0', max_length=20)),
                ('plan', models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/plan/', verbose_name='План помещения')),
                ('photo_inside', models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/inside/', verbose_name='Фото внутри')),
                ('photo_outside', models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/outside/', verbose_name='Фото снаружи')),
                ('additives', models.CharField(blank=True, default='0', max_length=200, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.user')),
            ],
            options={
                'verbose_name': 'Презентация',
                'verbose_name_plural': 'Презентации',
            },
        ),
    ]
