# Generated by Django 5.1.7 on 2025-03-24 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_remove_presentation_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Presentation',
            new_name='Presentations',
        ),
    ]
