# Generated by Django 5.1.7 on 2025-03-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_rename_presentation_presentations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentations',
            name='phone_number',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='presentations',
            name='user_id',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
