# Generated by Django 5.1.7 on 2025-03-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_alter_presentations_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentations',
            name='additives',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='presentations',
            name='adress',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='presentations',
            name='height',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='presentations',
            name='photo_inside',
            field=models.FileField(default='0', upload_to='uploads/%Y/%m/%d/photos/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='presentations',
            name='photo_outside',
            field=models.FileField(default='0', upload_to='uploads/%Y/%m/%d/photos/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='presentations',
            name='plan',
            field=models.FileField(default=0, upload_to=''),
        ),
        migrations.AddField(
            model_name='presentations',
            name='power',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='presentations',
            name='rate',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='presentations',
            name='square',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='presentations',
            name='type_rent',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='presentations',
            name='water_supply',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='presentations',
            name='presentation',
            field=models.FileField(upload_to='uploads/%Y/%m/%d/pres/', verbose_name='Файл презентации'),
        ),
    ]
