# Generated by Django 5.1.7 on 2025-03-24 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_presentations_additives_presentations_adress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentations',
            name='additives',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AlterField(
            model_name='presentations',
            name='adress',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='presentations',
            name='height',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='presentations',
            name='phone_number',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='presentations',
            name='photo_inside',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/photos/'),
        ),
        migrations.AlterField(
            model_name='presentations',
            name='photo_outside',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/photos/'),
        ),
        migrations.AlterField(
            model_name='presentations',
            name='plan',
            field=models.FileField(default='0', upload_to=''),
        ),
        migrations.AlterField(
            model_name='presentations',
            name='power',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='presentations',
            name='presentation',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/pres/', verbose_name='Файл презентации'),
        ),
        migrations.AlterField(
            model_name='presentations',
            name='rate',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='presentations',
            name='square',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='presentations',
            name='type_rent',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='presentations',
            name='user_id',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='presentations',
            name='water_supply',
            field=models.CharField(default='0', max_length=30),
        ),
    ]
