# Generated by Django 5.1.7 on 2025-03-25 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_alter_presentations_additives_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presentations',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='presentations',
            name='user_id',
        ),
        migrations.AddField(
            model_name='presentations',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='bot.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='presentations',
            name='photo_inside',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AlterField(
            model_name='presentations',
            name='photo_outside',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AlterField(
            model_name='presentations',
            name='plan',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
